import * as THREE from 'three';
import { chamferBox, place } from './Parts.js';

/**
 * Procedural first-person arms.
 *
 * Most browser shooters ship a floating gun and hope nobody notices. They do:
 * absent hands are the single most obvious "this is a demo" tell in a
 * first-person frame. So this builds a real hand — a nineteen-bone skeleton
 * (four fingers x 3, thumb x 3, palm, wrist, forearm), swept-tube geometry with
 * superelliptical cross-sections so the fingers read as gloved rather than as
 * sausages, knuckle armour, a cuff and a sleeve — and skins it with blended
 * weights across each joint so the creases fold instead of pinching.
 *
 * Canonical build frame (right hand): fingers along +Z, palm faces -Y, thumb
 * toward -X. The left hand is generated by mirroring X and flipping winding, so
 * both hands share one authoring path.
 */

/* -------------------------------------------------------------------- */
/* skeleton definition                                                    */
/* -------------------------------------------------------------------- */

const FINGERS = [
  { name: 'index', x: -0.0205, z: 0.0870, seg: [0.0420, 0.0262, 0.0196], r: [0.0098, 0.0090, 0.0080, 0.0068], spread: -0.055 },
  { name: 'middle', x: -0.0068, z: 0.0905, seg: [0.0452, 0.0292, 0.0206], r: [0.0100, 0.0092, 0.0082, 0.0068], spread: -0.012 },
  { name: 'ring', x: 0.0068, z: 0.0875, seg: [0.0424, 0.0276, 0.0198], r: [0.0095, 0.0088, 0.0078, 0.0065], spread: 0.026 },
  { name: 'pinky', x: 0.0202, z: 0.0800, seg: [0.0338, 0.0214, 0.0174], r: [0.0084, 0.0078, 0.0070, 0.0058], spread: 0.070 },
];

const THUMB = {
  name: 'thumb',
  base: [-0.0272, 0.0012, 0.0180],
  seg: [0.0350, 0.0300, 0.0224],
  r: [0.0128, 0.0110, 0.0096, 0.0082],
};

/**
 * Rest pose and every entry in HAND_POSES author **flexion as a negative
 * number** because "curl the finger down" reading as a negative value is what
 * an animator expects. The skeleton's actual flexion axis is +X (fingers run
 * along +Z, the palm faces -Y, so bending toward the palm is a positive
 * rotation about X), so the sign is inverted in exactly one place — `poseQuat`.
 */
const REST = {
  forearm: [0, 0, 0],
  wrist: [0, 0, 0],
  palm: [0, 0, 0],
  index1: [-0.16, 0, 0], index2: [-0.22, 0, 0], index3: [-0.16, 0, 0],
  middle1: [-0.18, 0, 0], middle2: [-0.24, 0, 0], middle3: [-0.18, 0, 0],
  ring1: [-0.19, 0, 0], ring2: [-0.25, 0, 0], ring3: [-0.19, 0, 0],
  pinky1: [-0.21, 0, 0], pinky2: [-0.27, 0, 0], pinky3: [-0.20, 0, 0],
  thumb1: [0.10, 0.62, -0.30], thumb2: [0.06, 0.34, 0], thumb3: [0.04, 0.26, 0],
};

/**
 * Hand poses. Values are XYZ Euler triples per bone; anything omitted falls
 * back to REST. Flexion is -X on the fingers (they curl toward the palm).
 */
export const HAND_POSES = {
  rest: {},

  /** Firing grip: full wrap, trigger finger indexed on the blade. */
  grip: {
    index1: [-0.82, 0.02, 0], index2: [-0.80, 0, 0], index3: [-0.36, 0, 0],
    middle1: [-1.06, 0.01, 0], middle2: [-1.34, 0, 0], middle3: [-0.86, 0, 0],
    ring1: [-1.12, 0, 0], ring2: [-1.40, 0, 0], ring3: [-0.92, 0, 0],
    pinky1: [-1.16, -0.03, 0], pinky2: [-1.42, 0, 0], pinky3: [-0.94, 0, 0],
    thumb1: [0.30, 0.76, -0.52], thumb2: [0.16, 0.86, 0], thumb3: [0.10, 0.60, 0],
  },

  /** Trigger broken — the index finger pulls straight back. */
  gripFire: {
    index1: [-0.98, 0.02, 0], index2: [-0.96, 0, 0], index3: [-0.52, 0, 0],
    middle1: [-1.08, 0.01, 0], middle2: [-1.36, 0, 0], middle3: [-0.88, 0, 0],
    ring1: [-1.14, 0, 0], ring2: [-1.42, 0, 0], ring3: [-0.94, 0, 0],
    pinky1: [-1.18, -0.03, 0], pinky2: [-1.44, 0, 0], pinky3: [-0.96, 0, 0],
    thumb1: [0.30, 0.78, -0.52], thumb2: [0.16, 0.88, 0], thumb3: [0.10, 0.62, 0],
  },

  /** Support hand around a handguard: thumb over the top, C-clamp. */
  support: {
    index1: [-0.96, 0.02, 0], index2: [-1.10, 0, 0], index3: [-0.62, 0, 0],
    middle1: [-1.10, 0.01, 0], middle2: [-1.24, 0, 0], middle3: [-0.72, 0, 0],
    ring1: [-1.14, 0, 0], ring2: [-1.28, 0, 0], ring3: [-0.76, 0, 0],
    pinky1: [-1.18, -0.02, 0], pinky2: [-1.30, 0, 0], pinky3: [-0.78, 0, 0],
    thumb1: [0.34, 0.30, -0.18], thumb2: [0.26, 0.10, 0], thumb3: [0.16, 0.06, 0],
  },

  /** Flat, fingers together — reaching for a magazine. */
  open: {
    index1: [-0.06, 0.03, 0], index2: [-0.08, 0, 0], index3: [-0.04, 0, 0],
    middle1: [-0.05, 0.01, 0], middle2: [-0.07, 0, 0], middle3: [-0.04, 0, 0],
    ring1: [-0.06, 0, 0], ring2: [-0.08, 0, 0], ring3: [-0.04, 0, 0],
    pinky1: [-0.09, -0.03, 0], pinky2: [-0.10, 0, 0], pinky3: [-0.05, 0, 0],
    thumb1: [0.02, 0.30, -0.44], thumb2: [0, 0.10, 0], thumb3: [0, 0.06, 0],
  },

  /** Pinching a magazine between thumb and fingers. */
  pinch: {
    index1: [-0.62, 0.04, 0], index2: [-0.42, 0, 0], index3: [-0.22, 0, 0],
    middle1: [-0.70, 0.01, 0], middle2: [-0.50, 0, 0], middle3: [-0.26, 0, 0],
    ring1: [-0.78, 0, 0], ring2: [-0.58, 0, 0], ring3: [-0.30, 0, 0],
    pinky1: [-0.86, -0.03, 0], pinky2: [-0.66, 0, 0], pinky3: [-0.34, 0, 0],
    thumb1: [0.34, 0.58, -0.36], thumb2: [0.20, 0.48, 0], thumb3: [0.12, 0.34, 0],
  },

  /** Closed fist — slapping a bolt release or a magazine home. */
  fist: {
    index1: [-1.34, 0.02, 0], index2: [-1.52, 0, 0], index3: [-1.02, 0, 0],
    middle1: [-1.38, 0.01, 0], middle2: [-1.56, 0, 0], middle3: [-1.06, 0, 0],
    ring1: [-1.40, 0, 0], ring2: [-1.58, 0, 0], ring3: [-1.08, 0, 0],
    pinky1: [-1.42, -0.03, 0], pinky2: [-1.60, 0, 0], pinky3: [-1.10, 0, 0],
    thumb1: [0.42, 0.88, -0.40], thumb2: [0.24, 1.02, 0], thumb3: [0.16, 0.74, 0],
  },

  /** Hooked around a charging handle / bolt knob. */
  hook: {
    index1: [-1.20, 0.06, 0], index2: [-1.30, 0, 0], index3: [-0.60, 0, 0],
    middle1: [-1.24, 0.02, 0], middle2: [-1.34, 0, 0], middle3: [-0.62, 0, 0],
    ring1: [-1.10, 0, 0], ring2: [-1.20, 0, 0], ring3: [-0.58, 0, 0],
    pinky1: [-1.00, -0.04, 0], pinky2: [-1.10, 0, 0], pinky3: [-0.54, 0, 0],
    thumb1: [0.44, 0.94, -0.34], thumb2: [0.26, 1.06, 0], thumb3: [0.18, 0.78, 0],
  },
};

/* -------------------------------------------------------------------- */
/* mesh builder                                                           */
/* -------------------------------------------------------------------- */

class SkinBuilder {
  constructor(flip) {
    this.pos = [];
    this.nrm = [];
    this.uv = [];
    this.col = [];
    this.si = [];
    this.sw = [];
    this.idx = [];
    this.flip = flip ? -1 : 1;
  }

  vertex(p, n, u, v, bones, weights, shade = 1) {
    this.pos.push(p.x, p.y, p.z);
    this.nrm.push(n.x, n.y, n.z);
    this.uv.push(u, v);
    this.col.push(shade, shade, shade);
    this.si.push(bones[0] | 0, bones[1] | 0, bones[2] | 0, bones[3] | 0);
    this.sw.push(weights[0] || 0, weights[1] || 0, weights[2] || 0, weights[3] || 0);
    return this.pos.length / 3 - 1;
  }

  quad(a, b, c, d) {
    if (this.flip < 0) { this.tri(a, c, b); this.tri(a, d, c); }
    else { this.tri(a, b, c); this.tri(a, c, d); }
  }

  tri(a, b, c) { this.idx.push(a, b, c); }

  build() {
    const g = new THREE.BufferGeometry();
    g.setAttribute('position', new THREE.Float32BufferAttribute(this.pos, 3));
    g.setAttribute('normal', new THREE.Float32BufferAttribute(this.nrm, 3));
    g.setAttribute('uv', new THREE.Float32BufferAttribute(this.uv, 2));
    g.setAttribute('color', new THREE.Float32BufferAttribute(this.col, 3));
    g.setAttribute('skinIndex', new THREE.Uint16BufferAttribute(this.si, 4));
    g.setAttribute('skinWeight', new THREE.Float32BufferAttribute(this.sw, 4));
    g.setIndex(this.idx);
    g.computeVertexNormals();
    g.computeBoundingSphere();
    return g;
  }

  get empty() { return this.idx.length === 0; }
}

const _up = new THREE.Vector3(0, 1, 0);
const _alt = new THREE.Vector3(1, 0, 0);

/** Superelliptical ring — rounded-rectangle cross-section, not a circle. */
function ringPoint(out, a, rx, ry, n) {
  const c = Math.cos(a), s = Math.sin(a);
  const p = 2 / n;
  out.set(
    Math.sign(c) * Math.pow(Math.abs(c), p) * rx,
    Math.sign(s) * Math.pow(Math.abs(s), p) * ry,
    0,
  );
  return out;
}

/**
 * Sweep a tube along a joint polyline with per-ring radii and blended skin
 * weights. `joints` is [{p:Vector3, bone:index}] and `radii` is [[rx,ry], ...]
 * one per joint (plus the tip).
 */
function sweep(builder, joints, radii, opts = {}) {
  const segs = opts.segments ?? 9;
  const nExp = opts.exponent ?? 3.2;
  const sub = opts.sub ?? 3;
  const shade = opts.shade ?? 1;
  const rings = [];

  const dir = new THREE.Vector3();
  const nx = new THREE.Vector3();
  const ny = new THREE.Vector3();
  const tmp = new THREE.Vector3();
  const pt = new THREE.Vector3();
  let arc = 0;

  for (let i = 0; i < joints.length - 1; i++) {
    const a = joints[i], b = joints[i + 1];
    dir.subVectors(b.p, a.p);
    const segLen = dir.length() || 1e-5;
    dir.multiplyScalar(1 / segLen);
    const ref = Math.abs(dir.dot(_up)) > 0.92 ? _alt : _up;
    nx.crossVectors(ref, dir).normalize();
    ny.crossVectors(dir, nx).normalize();

    const count = i === joints.length - 2 ? sub + 1 : sub;
    for (let s = 0; s < count; s++) {
      const u = s / sub;
      const t = i + u;
      // blend the two bones across the joint so the crease folds smoothly
      let w0 = 1, b0 = a.bone, b1 = a.bone;
      if (u < 0.34 && i > 0) {
        b1 = joints[i - 1].bone;
        w0 = 0.55 + (u / 0.34) * 0.45;
      }
      const r0 = radii[i], r1 = radii[i + 1];
      let rx = r0[0] + (r1[0] - r0[0]) * u;
      let ry = r0[1] + (r1[1] - r0[1]) * u;
      // knuckle swell at the head of each bone
      if (opts.knuckles && u < 0.3 && i > 0) {
        const k = 1 + 0.16 * (1 - u / 0.3);
        rx *= k; ry *= k;
      }
      const ring = [];
      const vcoord = arc + u * segLen;
      for (let k = 0; k < segs; k++) {
        const ang = (k / segs) * Math.PI * 2;
        ringPoint(pt, ang, rx, ry, nExp);
        tmp.copy(a.p)
          .addScaledVector(dir, u * segLen)
          .addScaledVector(nx, pt.x)
          .addScaledVector(ny, pt.y);
        const n = tmp.clone().sub(
          new THREE.Vector3().copy(a.p).addScaledVector(dir, u * segLen),
        ).normalize();
        // palm side sits in shadow, knuckle side catches light
        const sh = shade * (0.82 + 0.18 * (0.5 - 0.5 * Math.sin(ang)));
        ring.push(builder.vertex(tmp, n, k / segs, vcoord * 12, [b0, b1, 0, 0], [w0, 1 - w0, 0, 0], sh));
      }
      rings.push(ring);
    }
    arc += segLen;
  }

  for (let i = 0; i < rings.length - 1; i++) {
    const A = rings[i], B = rings[i + 1];
    for (let k = 0; k < segs; k++) {
      const k2 = (k + 1) % segs;
      builder.quad(A[k], A[k2], B[k2], B[k]);
    }
  }

  // tip cap
  if (opts.cap !== false) {
    const last = rings[rings.length - 1];
    const tip = joints[joints.length - 1];
    const tipDir = new THREE.Vector3().subVectors(tip.p, joints[joints.length - 2].p).normalize();
    const r = radii[radii.length - 1];
    const centre = tip.p.clone().addScaledVector(tipDir, Math.max(r[0], r[1]) * 0.62);
    const ci = builder.vertex(centre, tipDir, 0.5, 0, [tip.bone, tip.bone, 0, 0], [1, 0, 0, 0], shade * 0.95);
    for (let k = 0; k < segs; k++) {
      const k2 = (k + 1) % segs;
      if (builder.flip < 0) builder.tri(last[k], ci, last[k2]);
      else builder.tri(last[k], last[k2], ci);
    }
  }
  return rings;
}

/** Append a plain BufferGeometry rigidly weighted to one bone. */
function appendRigid(builder, geom, matrix, bone, shade = 1) {
  const g = geom.index ? geom.toNonIndexed() : geom;
  if (!g.attributes.normal) g.computeVertexNormals();
  g.applyMatrix4(matrix);
  const pos = g.attributes.position;
  const nrm = g.attributes.normal;
  const p = new THREE.Vector3();
  const n = new THREE.Vector3();
  const base = builder.pos.length / 3;
  for (let i = 0; i < pos.count; i++) {
    p.fromBufferAttribute(pos, i);
    n.fromBufferAttribute(nrm, i);
    builder.vertex(p, n, p.x * 24, p.z * 24, [bone, bone, 0, 0], [1, 0, 0, 0], shade);
  }
  for (let i = 0; i < pos.count; i += 3) {
    if (builder.flip < 0) builder.tri(base + i, base + i + 2, base + i + 1);
    else builder.tri(base + i, base + i + 1, base + i + 2);
  }
  g.dispose?.();
}

/* -------------------------------------------------------------------- */
/* assembly                                                               */
/* -------------------------------------------------------------------- */

/**
 * @param {Object} palette   from models/Palette.js
 * @param {Object} opts      {side:'right'|'left', forearm:number, sleeve:boolean}
 * @returns {{root:THREE.Object3D, bones:Object, skeleton:THREE.Skeleton,
 *            meshes:THREE.SkinnedMesh[], applyPose:Function}}
 */
export function buildHand(palette, opts = {}) {
  // The tables above describe a LEFT hand (thumb toward -X, dorsal +Y, fingers
  // +Z is a left-handed triple); the right hand is the mirror, which also means
  // its triangle winding has to be reversed.
  const left = opts.side === 'left';
  const sx = left ? 1 : -1;
  const mirrored = sx < 0;
  const forearmLen = opts.forearm ?? 0.300;

  /* ---- skeleton ---- */
  const bones = {};
  const list = [];
  const mk = (name, parent, p) => {
    const b = new THREE.Bone();
    b.name = name;
    b.position.set(p[0] * sx, p[1], p[2]);
    const r = REST[name] || [0, 0, 0];
    // -r[0]: authored flexion is negative, the skeleton flexes on +X
    b.rotation.set(-r[0], r[1] * sx, r[2] * sx);
    if (parent) parent.add(b);
    bones[name] = b;
    b.userData.index = list.length;
    list.push(b);
    return b;
  };

  // The wrist is the root: the socket places the *hand* on the weapon, and the
  // forearm hangs off it as a sibling of the palm so it can be aimed back at
  // the shoulder without dragging the grip out of position.
  const wrist = mk('wrist', null, [0, 0, 0]);
  const forearm = mk('forearm', wrist, [0, 0, 0]);
  const palm = mk('palm', wrist, [0, 0, 0]);

  for (const f of FINGERS) {
    let parent = palm;
    let base = [f.x, 0, f.z];
    for (let i = 0; i < 3; i++) {
      const name = `${f.name}${i + 1}`;
      const b = mk(name, parent, i === 0 ? base : [0, 0, f.seg[i - 1]]);
      if (i === 0) b.rotation.y = f.spread * sx + (REST[name]?.[1] ?? 0) * sx;
      parent = b;
    }
  }
  {
    let parent = palm;
    for (let i = 0; i < 3; i++) {
      const name = `thumb${i + 1}`;
      parent = mk(name, parent, i === 0 ? THUMB.base : [0, 0, THUMB.seg[i - 1]]);
    }
  }

  wrist.updateMatrixWorld(true);
  const skeleton = new THREE.Skeleton(list);

  const wp = (b) => new THREE.Vector3().setFromMatrixPosition(b.matrixWorld);
  const bi = (name) => bones[name].userData.index;

  /* ---- skin ---- */
  const skin = new SkinBuilder(mirrored);
  const pads = new SkinBuilder(mirrored);
  const strap = new SkinBuilder(mirrored);

  // forearm + wrist: one long taper into the hand, authored down the bone's -Z
  const at = (z) => new THREE.Vector3(0, 0, z);
  sweep(skin, [
    { p: at(-forearmLen), bone: bi('forearm') },
    { p: at(-forearmLen * 0.62), bone: bi('forearm') },
    { p: at(-forearmLen * 0.22), bone: bi('forearm') },
    { p: at(-0.004), bone: bi('wrist') },
  ], [
    [0.0480, 0.0455], [0.0430, 0.0398], [0.0348, 0.0312], [0.0312, 0.0268],
  ], { segments: 12, exponent: 2.6, sub: 3, cap: false, shade: 0.94 });

  // palm block: a swept slab from the wrist to the knuckle row
  const knuckleMid = wp(bones.middle1);
  sweep(skin, [
    { p: wp(wrist), bone: bi('wrist') },
    { p: wp(wrist).clone().lerp(knuckleMid, 0.34), bone: bi('palm') },
    { p: wp(wrist).clone().lerp(knuckleMid, 0.72), bone: bi('palm') },
    { p: knuckleMid.clone().addScaledVector(new THREE.Vector3(0, 0, 1), 0.004), bone: bi('palm') },
  ], [
    [0.0312, 0.0268], [0.0392, 0.0224], [0.0430, 0.0192], [0.0424, 0.0176],
  ], { segments: 14, exponent: 3.8, sub: 3, cap: false, shade: 1.0 });

  // thenar eminence (the muscle at the base of the thumb) — asymmetric bulge
  {
    const m = new THREE.Matrix4().compose(
      wp(bones.thumb1).clone().lerp(wp(wrist), 0.32).add(new THREE.Vector3(0, -0.004, 0)),
      new THREE.Quaternion().setFromEuler(new THREE.Euler(0.1, 0.35 * sx, 0)),
      new THREE.Vector3(1, 1, 1),
    );
    appendRigid(skin, chamferBox(0.024, 0.026, 0.048, 0.008, { curveSegments: 3 }), m, bi('palm'), 0.98);
  }

  // fingers
  for (const f of FINGERS) {
    const j = [];
    const r = [];
    for (let i = 0; i < 3; i++) {
      j.push({ p: wp(bones[`${f.name}${i + 1}`]), bone: bi(`${f.name}${i + 1}`) });
      r.push([f.r[i], f.r[i] * 0.88]);
    }
    const tipBone = bones[`${f.name}3`];
    const tip = new THREE.Vector3(0, 0, f.seg[2]).applyMatrix4(tipBone.matrixWorld);
    j.push({ p: tip, bone: bi(`${f.name}3`) });
    r.push([f.r[3], f.r[3] * 0.86]);
    sweep(skin, j, r, { segments: 9, exponent: 3.0, sub: 3, knuckles: true, shade: 1.0 });
  }

  // thumb
  {
    const j = [];
    const r = [];
    for (let i = 0; i < 3; i++) {
      j.push({ p: wp(bones[`thumb${i + 1}`]), bone: bi(`thumb${i + 1}`) });
      r.push([THUMB.r[i], THUMB.r[i] * 0.86]);
    }
    const tip = new THREE.Vector3(0, 0, THUMB.seg[2]).applyMatrix4(bones.thumb3.matrixWorld);
    j.push({ p: tip, bone: bi('thumb3') });
    r.push([THUMB.r[3], THUMB.r[3] * 0.84]);
    sweep(skin, j, r, { segments: 9, exponent: 3.0, sub: 3, knuckles: true, shade: 0.98 });
  }

  /* ---- glove hard parts ---- */
  // knuckle armour: one moulded pad per proximal finger bone
  for (const f of FINGERS) {
    const b = bones[`${f.name}1`];
    const m = new THREE.Matrix4().compose(
      wp(b).clone().add(new THREE.Vector3(0, f.r[0] * 0.78, 0.004)),
      new THREE.Quaternion().setFromEuler(new THREE.Euler(-0.2, 0, 0)),
      new THREE.Vector3(1, 1, 1),
    );
    appendRigid(pads, chamferBox(f.r[0] * 1.85, 0.0052, 0.0180, 0.0018, { curveSegments: 3 }), m, bi(`${f.name}1`), 1.0);
  }
  // dorsal plate across the back of the hand
  {
    const m = new THREE.Matrix4().compose(
      wp(wrist).clone().lerp(knuckleMid, 0.52).add(new THREE.Vector3(0, 0.0192, 0)),
      new THREE.Quaternion().setFromEuler(new THREE.Euler(-0.05, 0, 0)),
      new THREE.Vector3(1, 1, 1),
    );
    appendRigid(pads, chamferBox(0.0640, 0.0050, 0.0520, 0.0040, { curveSegments: 3 }), m, bi('palm'), 1.0);
    const m2 = new THREE.Matrix4().compose(
      wp(wrist).clone().lerp(knuckleMid, 0.52).add(new THREE.Vector3(0, 0.0224, 0)),
      new THREE.Quaternion(),
      new THREE.Vector3(1, 1, 1),
    );
    appendRigid(pads, chamferBox(0.0300, 0.0028, 0.0300, 0.0026, { curveSegments: 3 }), m2, bi('palm'), 1.06);
  }
  // palm grip patch (the rubberised panel that actually touches the weapon)
  {
    const m = new THREE.Matrix4().compose(
      wp(wrist).clone().lerp(knuckleMid, 0.55).add(new THREE.Vector3(0, -0.0186, 0)),
      new THREE.Quaternion(),
      new THREE.Vector3(1, 1, 1),
    );
    appendRigid(pads, chamferBox(0.0560, 0.0034, 0.0620, 0.0022, { curveSegments: 3 }), m, bi('palm'), 0.86);
  }

  /* ---- cuff + sleeve ---- */
  const cuffAt = at(-0.058);
  {
    const m = new THREE.Matrix4().compose(cuffAt, new THREE.Quaternion(), new THREE.Vector3(1, 1, 1));
    appendRigid(strap, chamferBox(0.0760, 0.0700, 0.0300, 0.0090, { curveSegments: 4 }), m, bi('forearm'), 1.0);
    const buckle = new THREE.Matrix4().compose(
      cuffAt.clone().add(new THREE.Vector3(0, 0.0330, 0.0)),
      new THREE.Quaternion(),
      new THREE.Vector3(1, 1, 1),
    );
    appendRigid(strap, chamferBox(0.0250, 0.0060, 0.0210, 0.0020, { curveSegments: 3 }), buckle, bi('forearm'), 1.1);
  }
  if (opts.sleeve !== false) {
    sweep(strap, [
      { p: at(-forearmLen - 0.07), bone: bi('forearm') },
      { p: at(-forearmLen * 0.86), bone: bi('forearm') },
      { p: at(-forearmLen * 0.52), bone: bi('forearm') },
      { p: at(-0.088), bone: bi('forearm') },
    ], [
      [0.0640, 0.0620], [0.0590, 0.0562], [0.0512, 0.0486], [0.0448, 0.0420],
    ], { segments: 14, exponent: 2.4, sub: 2, cap: false, shade: 0.92 });
  }

  /* ---- meshes ---- */
  const root = new THREE.Object3D();
  root.name = left ? 'handLeft' : 'handRight';
  root.add(wrist);

  const meshes = [];
  const mkMesh = (builder, material, name) => {
    if (builder.empty) return null;
    const mesh = new THREE.SkinnedMesh(builder.build(), material);
    mesh.name = name;
    mesh.frustumCulled = false;
    mesh.castShadow = false;
    mesh.receiveShadow = false;
    mesh.bind(skeleton, new THREE.Matrix4());
    root.add(mesh);
    meshes.push(mesh);
    return mesh;
  };
  mkMesh(skin, palette.glove, 'glove');
  mkMesh(pads, palette.glovePad, 'glovePads');
  mkMesh(strap, palette.webbing, 'cuff');

  /* ---- posing ---- */
  const targets = new Map();   // bone -> Quaternion
  const _eu = new THREE.Euler();
  const _qt = new THREE.Quaternion();

  function poseQuat(name, pose) {
    const r = (pose && pose[name]) || REST[name] || [0, 0, 0];
    let y = r[1] * sx;
    let z = r[2] * sx;
    // finger spread is baked per-finger and must survive posing
    for (const f of FINGERS) if (name === `${f.name}1`) y += f.spread * sx;
    _eu.set(-r[0], y, z, 'XYZ');
    return _qt.setFromEuler(_eu).clone();
  }

  /**
   * Blend the skeleton toward a named pose.
   * @param {string} name  key in HAND_POSES
   * @param {number} t     0..1 blend factor applied this frame
   */
  function applyPose(name, t = 1) {
    const pose = HAND_POSES[name] || HAND_POSES.rest;
    for (const b of list) {
      if (b.name === 'forearm' || b.name === 'wrist') continue;
      let q = targets.get(b.name);
      if (!q) { q = new THREE.Quaternion(); targets.set(b.name, q); }
      q.copy(poseQuat(b.name, pose));
      b.quaternion.slerp(q, THREE.MathUtils.clamp(t, 0, 1));
    }
  }

  /** Snap instantly, used on equip and by the capture harness. */
  function setPose(name) { applyPose(name, 1); }

  /**
   * Aim the forearm back toward the shoulder without disturbing the grip.
   * The forearm bone shares the hand root's frame and its mesh is built on the
   * axis, so these angles are *not* mirrored — each hand is aimed explicitly.
   */
  function setForearm(x, y, z) {
    bones.forearm.rotation.set(x, y, z);
  }

  setPose('rest');

  return {
    root, bones, skeleton, meshes, applyPose, setPose, setForearm,
    side: left ? 'left' : 'right',
  };
}
